### ISSUE TITLE
I have a error

### ISSUE THREAD

**Issue by abollol** [scmethods/scregclust#1]
plot_module_count_helper(list_of_fits=fit, penalization = 0.10)
错误于fit$penalization: $ operator is invalid for atomic vectors

**Comment by cyianor** [comment]
Hi @abollol, you are providing very little context. My assumption is that `fit` is only a single run of scregclust. Is that correct? `plot_module_count_helper` is meant to be called on a list of multiple runs of scregclust with varying initial module counts.

See the [docs](https://scmethods.github.io/scregclust/reference/plot_module_count_helper.html)
