### ISSUE TITLE
sample_assignment means batch？

### ISSUE THREAD

**Issue by Li-ZhiD** [scmethods/scregclust#3]
Hi, nice tool! 

Does "sample_assignment" mean batch? Or how to deal with batch effects? "vars.to.regress" in SCTransform？

**Comment by cyianor** [comment]
Hi,

`sample_assignment` can be seen as a batch indicator. Note, however, that we do not perform any elaborate batch-normalization. If you supply the batches in `sample_assignment` (one entry per cell) then each batch will be centered separately (if `center = TRUE`) and while splitting the data, cells are sampled with stratification across batches.

**Comment by Li-ZhiD** [comment]
Thank you! Can we provide cell type information or how can we link the modules and cell types?

**Comment by idacharlottalarsson** [comment]
Hi! To link the modules to cell types, what we do in the paper is to overlap the list of genes in each module with gene signatures of known cell types using Jaccard index (e.g. to create figure 1c, 3b, 4b and 5a). That, together with actually taking a look at the genes included in a module and the regulators controlling it, will usually give a very good idea of what cell type the module represents :)

**Comment by Li-ZhiD** [comment]
Thank you!
