### ISSUE TITLE
scregclust takes too long time

### ISSUE THREAD

**Issue by Pang-Ka** [scmethods/scregclust#5]
Dear authors, 
I used a dataset with 20541 features and 19840 samples to run `scregclust` with the following codes:
` fit <- scregclust( z, genesymbols, is_regulator, penalization = seq(0.1, 0.5, 0.05), n_modules = 10L, n_cycles = 50L, noise_threshold = 0.05)`

 It took about 18 hours to complete one cycle of one penalization score. Is there any way to speed up this process?
Many thanks!

![WeChat2969606b4b314c30c0de326b4df214ed](https://github.com/user-attachments/assets/d2dd1a60-5732-47d7-8bdd-9ffbc7f7ad10)

**Comment by cyianor** [comment]
Hi,
How many tentative regulators are you considering, i.e. what is `sum(is_regulator)`?

Also, what kind of computer are you running this on?

**Comment by Pang-Ka** [comment]
Hi,
I found the `sum(is_regulator)` is `1`, is it right?
My code is as follows:
`z <- GetAssayData(sc, layer = "scale.data")`
`dim(z) #[1] 20527 19840`
`out <- scregclust_format(z, mode = "TF")`
`is_regulator <- out$is_regulator`

I run the code with my MacBook Pro (Apple M1 Pro, MacOS 14.6.1)

**Comment by idacharlottalarsson** [comment]
Hi, 

Adding to Felix's answer above, I would strongly recommend that you include a feature selection step before running scregclust, e.g. only including the top XX most variable genes in your gene expression matrix. For sc-data generated from a UMI-based platform, e.g. 10X Genomics, I usually normalize my data using sctransform which by default returns the 3000 most variable genes (but this can be of course be changed to return more or less genes). Usually, including all 20000+ genes is unnecessary since most of them have zero variance and are therefore uninformative (as you can see already in your first run more than 16000 genes were placed in the noise cluster). Hopefully this will speed things up.

Let us know how it goes!

**Comment by Pang-Ka** [comment]
> Hi,
> 
> Adding to Felix's answer above, I would strongly recommend that you include a feature selection step before running scregclust, e.g. only including the top XX most variable genes in your gene expression matrix. For sc-data generated from a UMI-based platform, e.g. 10X Genomics, I usually normalize my data using sctransform which by default returns the 3000 most variable genes (but this can be of course be changed to return more or less genes). Usually, including all 20000+ genes is unnecessary since most of them have zero variance and are therefore uninformative (as you can see already in your first run more than 16000 genes were placed in the noise cluster). Hopefully this will speed things up.
> 
> Let us know how it goes!

Hi,

Thank you for your suggestion. Where can I set the feature number parameter? I normalized my data using `Seurat` and return 2000 top variable genes and I want to  use those variable genes to run `scregclust` more efficiently as you suggest.

Thanks.

**Comment by Pang-Ka** [comment]
> Hi,
> 
> Adding to Felix's answer above, I would strongly recommend that you include a feature selection step before running scregclust, e.g. only including the top XX most variable genes in your gene expression matrix. For sc-data generated from a UMI-based platform, e.g. 10X Genomics, I usually normalize my data using sctransform which by default returns the 3000 most variable genes (but this can be of course be changed to return more or less genes). Usually, including all 20000+ genes is unnecessary since most of them have zero variance and are therefore uninformative (as you can see already in your first run more than 16000 genes were placed in the noise cluster). Hopefully this will speed things up.
> 
> Let us know how it goes!

Thank you for your suggestions. I tried to use top 2000 variable genes to run scregclust, but I still got some ERROR:
`out <- scregclust_format(z, mode = "TF")`
`genesymbols <- VariableFeatures(sc)`
`sample_assignment <- out$sample_assignment`
`is_regulator <- out$is_regulator`
`mouseTF <- read.table('/Volumes/Data/allTFs_mm.txt')`
`ix<-which(genesymbols %in% mouseTF$V1)`
`is_regulator[ix]<-1`
`fit <- scregclust(z, genesymbols, is_regulator, 
                  penalization = seq(0.1, 0.5, 0.05),
                  n_modules = 10L, n_cycles = 50L, noise_threshold = 0.05)`

<img width="688" alt="image" src="https://github.com/user-attachments/assets/d93f40f1-72f0-4267-9c3d-bb63c861209d">

**Comment by idacharlottalarsson** [comment]
The error is due to the fact that your z-matrix and is_predictor vector is still of length/dimension 20527, but your genesymbols-vector is top 2000 genes. You need to start by reducing your z-matrix to only contain the top 2000 genes, and then run the code starting from the scregclust_format command. Something like this:

```
top2000<-VariableFeatures(sc)
z<-z[top2000,]
out <- scregclust_format(z, mode = "TF")
genesymbols <- out$genesymbols
sample_assignment <- out$sample_assignment
is_regulator <- out$is_regulator
fit <- scregclust(z, genesymbols, is_regulator,  penalization = seq(0.1, 0.5, 0.05), n_modules = 10L, n_cycles = 50L, noise_threshold = 0.05)
```
Hope it works now!

**Comment by Pang-Ka** [comment]
> The error is due to the fact that your z-matrix and is_predictor vector is still of length/dimension 20527, but your genesymbols-vector is top 2000 genes. You need to start by reducing your z-matrix to only contain the top 2000 genes, and then run the code starting from the scregclust_format command. Something like this:
> 
> ```
> top2000<-VariableFeatures(sc)
> z<-z[top2000,]
> out <- scregclust_format(z, mode = "TF")
> genesymbols <- out$genesymbols
> sample_assignment <- out$sample_assignment
> is_regulator <- out$is_regulator
> fit <- scregclust(z, genesymbols, is_regulator,  penalization = seq(0.1, 0.5, 0.05), n_modules = 10L, n_cycles = 50L, noise_threshold = 0.05)
> ```
> 
> Hope it works now!

Thank you for your help, it works now.

**Comment by cyianor** [comment]
> `sum(is_regulator)` is `1`

@Pang-Ka one more note. From what you wrote above, it seems like the transcription factor list that is used within `scregclust_format` might not be relevant for the dataset you are using. `sum(is_regulator)` tells you how many regulators will be considered during model building. While of course you can do this with only one regulator, you will not actually use any of `scregclust` advantages until you include more. Depending on the source of your data, you should maybe consider a different list of regulators.

On the other hand, the screenshot you posted in your first post, shows that there are at least 16 regulators in your dataset, so `sum(is_regulator)` should be 16 or larger.

You might want to double check this.
